"""Every picture the prose shows is one the recording command produces.

THIS IS THE HALF THE SCREENSHOT RUN CANNOT CHECK. `test_screenshots.py` records
what it is told to record. It cannot notice that the README points at a file
nobody generates any more, or that a picture was recorded and then never shown
to anybody. Both were true here: the README's hero image was captured by hand at
some commit, regenerated by no command, and stale for as long as anyone could
tell — it looked exactly like a maintained artifact.

So this runs in the ordinary suite, needs no browser and no server, and pairs
the two directions:

  - every image the docs reference exists on disk, and
  - every image on disk is one `looksatwords screenshots` writes.

The second is the one that bites. A picture nobody regenerates is not obviously
wrong at any single commit; it just drifts, silently, while the page around it
gets edited.

BOTH DIRECTIONS WERE MUTATED ON 2026-08-27 AND BOTH WENT RED. Adding
`![missing](docs/pics/does-not-exist.png)` to the README failed the first;
copying a recorded picture to `orphan-shot.png` failed the second. Restored,
nine pass. `test_the_recorder_writes_something` exists because both checks
compare against a parsed set, and a broken parse would have made them green
while checking nothing.
"""

import pathlib
import re

import pytest

REPO = pathlib.Path(__file__).resolve().parent.parent.parent
PICS = REPO / "docs" / "pics"
SHOOTER = pathlib.Path(__file__).parent / "test_screenshots.py"

# Markdown image and link targets that point into docs/pics/.
REF = re.compile(r"!?\[[^\]]*\]\(([^)]*docs/pics/[^)\s]+)\)")


def _documents():
    yield REPO / "README.md"
    yield from sorted((REPO / "docs").glob("*.md"))


def _referenced():
    """(document, path) for every docs/pics reference in the committed prose."""
    for doc in _documents():
        if not doc.exists():
            continue
        for target in REF.findall(doc.read_text(encoding="utf-8")):
            name = target.split("docs/pics/")[-1]
            yield doc.relative_to(REPO), name


def _recorded():
    """The filenames `test_screenshots.py` actually writes."""
    text = SHOOTER.read_text(encoding="utf-8")
    return set(re.findall(r'_shoot\(page,\s*"([^"]+)"\)', text))


def test_the_recorder_writes_something():
    """Guard the guard: if the parse breaks, both tests below pass vacuously."""
    recorded = _recorded()
    assert recorded, (
        "no `_shoot(page, \"...\")` calls were found in test_screenshots.py, so "
        "the two checks below would compare against an empty set and pass while "
        "checking nothing"
    )


@pytest.mark.parametrize("doc,name", list(_referenced()))
def test_every_pictured_file_exists(doc, name):
    assert (PICS / name).exists(), (
        f"{doc} shows docs/pics/{name} and no such file exists. "
        "Run `uv run looksatwords screenshots`."
    )


@pytest.mark.parametrize("name", sorted(p.name for p in PICS.glob("*.png")))
def test_every_committed_picture_is_regenerated_by_a_command(name):
    """A committed image no command rewrites is stale the moment the UI moves.

    The remedy is to record it in `test_screenshots.py` or to delete it — not to
    add it to an exemption list, which is how the first one survived.
    """
    assert name in _recorded(), (
        f"docs/pics/{name} is committed and nothing regenerates it. Either add a "
        "`_shoot` for it in test_screenshots.py, or delete it."
    )
